## UGent Environmental and Energy Economics Seminar

- Nicolas Astier (Paris School of Economics, 2021)
- Pei Huang (ZEW Mannheim, 2022)
- Charlotte De Cannière (KU Leuven, 2022)
- Marta Talevi (University College Dublin, 2023)
- Kenneth Gillingham (Yale University, 2024)
- Paige Weber (UC Berkeley, 2024)
- Geert Goeyvaerts (KU Leuven, 2024)
- Justus Böning (KU Leuven, 2024)
- Emma Menegatti (Florence School of Regulation, 2025)
- Laurent Franckx (Federaal Planbureau, 2025)
- Estelle Cantillon (Université libre de Bruxelles, 2025)
- Elise Viadere (Université libre de Bruxelles, 2025)
- Ariane Bousquet (Université Lyon 2, LAET, 2025)
- Sébastien Houde (HEC Lausanne, 2025)
- Matthew Gordon (Paris School of Economics, 2025)
- Carles Mañó-Cabello (KU Leuven, 2026)
- Mirabelle Muuls (Imperial College London, 2026)
- Ulrike Morgalla (Max Planck Net Zero Lab, 2026)
- Reo Van Eynde (Universitat de Barcelona, 2026)
- Alice Lixuan Xu (Hertie School, 2026)
- Jason Harold (University of Galway, 2026)
